### ISSUE TITLE
composite struct literal net/mail.Address with unkeyed fields

### ISSUE THREAD

**Issue by bsr203** [jpoehls/gophermail#11]
Hello,

I get this error, when I use the package with App Engine. I use App Engine mail package when use with GAE, but for standalone version I use gophermail. I share code between them. 

src/github.com/jpoehls/gophermail/main.go:342:10: composite struct literal net/mail.Address with unkeyed fields

It can be solved by changing line 342

```
addr := mail.Address{input, ""}
```

to 

```
addr := mail.Address{Name: input, Address: ""}

```

thanks.

**Comment by jpoehls** [comment]
@bsr203: I just pushed the update you recommended. I'm going to close this issue but definitely reopen it if you still see the error. Thanks!
